// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend_profile.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	engine "github.com/webitel/engine/grpc_api/engine"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteBackendProfileRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackendProfileRequest) Reset()         { *m = DeleteBackendProfileRequest{} }
func (m *DeleteBackendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBackendProfileRequest) ProtoMessage()    {}
func (*DeleteBackendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{0}
}

func (m *DeleteBackendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackendProfileRequest.Unmarshal(m, b)
}
func (m *DeleteBackendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackendProfileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBackendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackendProfileRequest.Merge(m, src)
}
func (m *DeleteBackendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBackendProfileRequest.Size(m)
}
func (m *DeleteBackendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackendProfileRequest proto.InternalMessageInfo

func (m *DeleteBackendProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteBackendProfileRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type PatchBackendProfileRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExpireDays           int32             `protobuf:"varint,3,opt,name=expire_days,json=expireDays,proto3" json:"expire_days,omitempty"`
	MaxSize              int64             `protobuf:"varint,4,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Priority             int32             `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Properties           map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Disabled             bool              `protobuf:"varint,8,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Fields               []string          `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	DomainId             int64             `protobuf:"varint,10,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PatchBackendProfileRequest) Reset()         { *m = PatchBackendProfileRequest{} }
func (m *PatchBackendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*PatchBackendProfileRequest) ProtoMessage()    {}
func (*PatchBackendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{1}
}

func (m *PatchBackendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchBackendProfileRequest.Unmarshal(m, b)
}
func (m *PatchBackendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchBackendProfileRequest.Marshal(b, m, deterministic)
}
func (m *PatchBackendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchBackendProfileRequest.Merge(m, src)
}
func (m *PatchBackendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_PatchBackendProfileRequest.Size(m)
}
func (m *PatchBackendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchBackendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchBackendProfileRequest proto.InternalMessageInfo

func (m *PatchBackendProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PatchBackendProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PatchBackendProfileRequest) GetExpireDays() int32 {
	if m != nil {
		return m.ExpireDays
	}
	return 0
}

func (m *PatchBackendProfileRequest) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *PatchBackendProfileRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *PatchBackendProfileRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *PatchBackendProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PatchBackendProfileRequest) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *PatchBackendProfileRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *PatchBackendProfileRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type UpdateBackendProfileRequest struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExpireDays           int32             `protobuf:"varint,3,opt,name=expire_days,json=expireDays,proto3" json:"expire_days,omitempty"`
	MaxSize              int64             `protobuf:"varint,4,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Priority             int32             `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Properties           map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Disabled             bool              `protobuf:"varint,8,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DomainId             int64             `protobuf:"varint,9,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateBackendProfileRequest) Reset()         { *m = UpdateBackendProfileRequest{} }
func (m *UpdateBackendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBackendProfileRequest) ProtoMessage()    {}
func (*UpdateBackendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{2}
}

func (m *UpdateBackendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBackendProfileRequest.Unmarshal(m, b)
}
func (m *UpdateBackendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBackendProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBackendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBackendProfileRequest.Merge(m, src)
}
func (m *UpdateBackendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBackendProfileRequest.Size(m)
}
func (m *UpdateBackendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBackendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBackendProfileRequest proto.InternalMessageInfo

func (m *UpdateBackendProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateBackendProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateBackendProfileRequest) GetExpireDays() int32 {
	if m != nil {
		return m.ExpireDays
	}
	return 0
}

func (m *UpdateBackendProfileRequest) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *UpdateBackendProfileRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *UpdateBackendProfileRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *UpdateBackendProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateBackendProfileRequest) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *UpdateBackendProfileRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadBackendProfileRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBackendProfileRequest) Reset()         { *m = ReadBackendProfileRequest{} }
func (m *ReadBackendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBackendProfileRequest) ProtoMessage()    {}
func (*ReadBackendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{3}
}

func (m *ReadBackendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBackendProfileRequest.Unmarshal(m, b)
}
func (m *ReadBackendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBackendProfileRequest.Marshal(b, m, deterministic)
}
func (m *ReadBackendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBackendProfileRequest.Merge(m, src)
}
func (m *ReadBackendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBackendProfileRequest.Size(m)
}
func (m *ReadBackendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBackendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBackendProfileRequest proto.InternalMessageInfo

func (m *ReadBackendProfileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadBackendProfileRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchBackendProfileRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBackendProfileRequest) Reset()         { *m = SearchBackendProfileRequest{} }
func (m *SearchBackendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBackendProfileRequest) ProtoMessage()    {}
func (*SearchBackendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{4}
}

func (m *SearchBackendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBackendProfileRequest.Unmarshal(m, b)
}
func (m *SearchBackendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBackendProfileRequest.Marshal(b, m, deterministic)
}
func (m *SearchBackendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBackendProfileRequest.Merge(m, src)
}
func (m *SearchBackendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBackendProfileRequest.Size(m)
}
func (m *SearchBackendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBackendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBackendProfileRequest proto.InternalMessageInfo

func (m *SearchBackendProfileRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchBackendProfileRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchBackendProfileRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ListBackendProfile struct {
	Items                []*BackendProfile `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListBackendProfile) Reset()         { *m = ListBackendProfile{} }
func (m *ListBackendProfile) String() string { return proto.CompactTextString(m) }
func (*ListBackendProfile) ProtoMessage()    {}
func (*ListBackendProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{5}
}

func (m *ListBackendProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackendProfile.Unmarshal(m, b)
}
func (m *ListBackendProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackendProfile.Marshal(b, m, deterministic)
}
func (m *ListBackendProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackendProfile.Merge(m, src)
}
func (m *ListBackendProfile) XXX_Size() int {
	return xxx_messageInfo_ListBackendProfile.Size(m)
}
func (m *ListBackendProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackendProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackendProfile proto.InternalMessageInfo

func (m *ListBackendProfile) GetItems() []*BackendProfile {
	if m != nil {
		return m.Items
	}
	return nil
}

type BackendProfile struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            int64             `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            *engine.Lookup    `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            int64             `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            *engine.Lookup    `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DataSize             int64             `protobuf:"varint,6,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	DataCount            int64             `protobuf:"varint,7,opt,name=data_count,json=dataCount,proto3" json:"data_count,omitempty"`
	Name                 string            `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	ExpireDays           int32             `protobuf:"varint,9,opt,name=expire_days,json=expireDays,proto3" json:"expire_days,omitempty"`
	MaxSize              int64             `protobuf:"varint,10,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Priority             int32             `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	Type                 string            `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	Properties           map[string]string `protobuf:"bytes,13,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Disabled             bool              `protobuf:"varint,15,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BackendProfile) Reset()         { *m = BackendProfile{} }
func (m *BackendProfile) String() string { return proto.CompactTextString(m) }
func (*BackendProfile) ProtoMessage()    {}
func (*BackendProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{6}
}

func (m *BackendProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendProfile.Unmarshal(m, b)
}
func (m *BackendProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendProfile.Marshal(b, m, deterministic)
}
func (m *BackendProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendProfile.Merge(m, src)
}
func (m *BackendProfile) XXX_Size() int {
	return xxx_messageInfo_BackendProfile.Size(m)
}
func (m *BackendProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BackendProfile proto.InternalMessageInfo

func (m *BackendProfile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BackendProfile) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *BackendProfile) GetCreatedBy() *engine.Lookup {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *BackendProfile) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *BackendProfile) GetUpdatedBy() *engine.Lookup {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

func (m *BackendProfile) GetDataSize() int64 {
	if m != nil {
		return m.DataSize
	}
	return 0
}

func (m *BackendProfile) GetDataCount() int64 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BackendProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackendProfile) GetExpireDays() int32 {
	if m != nil {
		return m.ExpireDays
	}
	return 0
}

func (m *BackendProfile) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *BackendProfile) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *BackendProfile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BackendProfile) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *BackendProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BackendProfile) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type CreateBackendProfileRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpireDays           int32             `protobuf:"varint,2,opt,name=expire_days,json=expireDays,proto3" json:"expire_days,omitempty"`
	MaxSize              int64             `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Priority             int32             `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Type                 string            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Properties           map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Disabled             bool              `protobuf:"varint,8,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DomainId             int64             `protobuf:"varint,9,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateBackendProfileRequest) Reset()         { *m = CreateBackendProfileRequest{} }
func (m *CreateBackendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBackendProfileRequest) ProtoMessage()    {}
func (*CreateBackendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{7}
}

func (m *CreateBackendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackendProfileRequest.Unmarshal(m, b)
}
func (m *CreateBackendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackendProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateBackendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackendProfileRequest.Merge(m, src)
}
func (m *CreateBackendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBackendProfileRequest.Size(m)
}
func (m *CreateBackendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackendProfileRequest proto.InternalMessageInfo

func (m *CreateBackendProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBackendProfileRequest) GetExpireDays() int32 {
	if m != nil {
		return m.ExpireDays
	}
	return 0
}

func (m *CreateBackendProfileRequest) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *CreateBackendProfileRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *CreateBackendProfileRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateBackendProfileRequest) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *CreateBackendProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateBackendProfileRequest) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *CreateBackendProfileRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteBackendProfileRequest)(nil), "storage.DeleteBackendProfileRequest")
	proto.RegisterType((*PatchBackendProfileRequest)(nil), "storage.PatchBackendProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "storage.PatchBackendProfileRequest.PropertiesEntry")
	proto.RegisterType((*UpdateBackendProfileRequest)(nil), "storage.UpdateBackendProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "storage.UpdateBackendProfileRequest.PropertiesEntry")
	proto.RegisterType((*ReadBackendProfileRequest)(nil), "storage.ReadBackendProfileRequest")
	proto.RegisterType((*SearchBackendProfileRequest)(nil), "storage.SearchBackendProfileRequest")
	proto.RegisterType((*ListBackendProfile)(nil), "storage.ListBackendProfile")
	proto.RegisterType((*BackendProfile)(nil), "storage.BackendProfile")
	proto.RegisterMapType((map[string]string)(nil), "storage.BackendProfile.PropertiesEntry")
	proto.RegisterType((*CreateBackendProfileRequest)(nil), "storage.CreateBackendProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "storage.CreateBackendProfileRequest.PropertiesEntry")
}

func init() { proto.RegisterFile("backend_profile.proto", fileDescriptor_5d7b07ba17e92942) }

var fileDescriptor_5d7b07ba17e92942 = []byte{
	// 828 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x5f, 0x6f, 0xd3, 0x48,
	0x10, 0x97, 0xe3, 0x24, 0x8d, 0x27, 0x77, 0xe9, 0x69, 0x2f, 0xbd, 0x73, 0x9d, 0x6b, 0x2f, 0xe7,
	0x56, 0x77, 0xb9, 0x4a, 0x4d, 0xa4, 0x94, 0x07, 0x54, 0x89, 0x07, 0xda, 0x22, 0xfe, 0xa8, 0x0f,
	0x95, 0x03, 0xcf, 0xd1, 0x26, 0x9e, 0x86, 0x55, 0x13, 0xdb, 0xd8, 0x9b, 0xaa, 0x6e, 0x29, 0x42,
	0xbc, 0xf1, 0x80, 0x78, 0xe0, 0x03, 0xf0, 0x4d, 0xf8, 0x12, 0x7c, 0x05, 0x3e, 0x08, 0xf2, 0xda,
	0x35, 0x71, 0x1a, 0x3b, 0x41, 0x14, 0x24, 0xde, 0x76, 0x67, 0xd7, 0xbf, 0x99, 0xf9, 0xfd, 0x66,
	0xc6, 0x0b, 0x2b, 0x3d, 0xda, 0x3f, 0x41, 0xcb, 0xec, 0x3a, 0xae, 0x7d, 0xcc, 0x86, 0xd8, 0x74,
	0x5c, 0x9b, 0xdb, 0x64, 0xc9, 0xe3, 0xb6, 0x4b, 0x07, 0xa8, 0x11, 0xb4, 0x06, 0xcc, 0xc2, 0x56,
	0xdf, 0xb6, 0x3c, 0x1e, 0x1e, 0x6a, 0x7f, 0x0d, 0x6c, 0x7b, 0x30, 0xc4, 0x16, 0x75, 0x58, 0x8b,
	0x5a, 0x96, 0xcd, 0x29, 0x67, 0xb6, 0xe5, 0x85, 0xa7, 0xfa, 0x23, 0xa8, 0x1d, 0xe0, 0x10, 0x39,
	0xee, 0x85, 0xc8, 0x47, 0x21, 0xb0, 0x81, 0xcf, 0xc6, 0xe8, 0x71, 0x52, 0x81, 0x1c, 0x33, 0x55,
	0xa9, 0x2e, 0x35, 0x64, 0x23, 0xc7, 0x4c, 0x52, 0x03, 0xc5, 0xb4, 0x47, 0x94, 0x59, 0x5d, 0x66,
	0xaa, 0x39, 0x61, 0x2e, 0x85, 0x86, 0x87, 0xa6, 0xfe, 0x5e, 0x06, 0xed, 0x88, 0xf2, 0xfe, 0xd3,
	0xc5, 0xb0, 0x08, 0xe4, 0x2d, 0x3a, 0x42, 0x01, 0xa3, 0x18, 0x62, 0x4d, 0xfe, 0x86, 0x32, 0x9e,
	0x39, 0xcc, 0xc5, 0xae, 0x49, 0x7d, 0x4f, 0x95, 0xeb, 0x52, 0xa3, 0x60, 0x40, 0x68, 0x3a, 0xa0,
	0xbe, 0x47, 0x56, 0xa1, 0x34, 0xa2, 0x67, 0x5d, 0x8f, 0x9d, 0xa3, 0x9a, 0x17, 0x50, 0x4b, 0x23,
	0x7a, 0xd6, 0x61, 0xe7, 0x48, 0x34, 0x28, 0x39, 0x2e, 0xb3, 0x5d, 0xc6, 0x7d, 0xb5, 0x20, 0x3e,
	0x8c, 0xf7, 0xa4, 0x03, 0xe0, 0xb8, 0xb6, 0x83, 0x2e, 0x67, 0xe8, 0xa9, 0xc5, 0xba, 0xdc, 0x28,
	0xb7, 0x77, 0x9a, 0x11, 0x6d, 0xcd, 0xf4, 0xa0, 0x9b, 0x47, 0xf1, 0x57, 0xf7, 0x2c, 0xee, 0xfa,
	0xc6, 0x04, 0x0c, 0xa9, 0x43, 0xd9, 0x44, 0xaf, 0xef, 0x32, 0x27, 0x60, 0x54, 0x5d, 0x12, 0x79,
	0x4c, 0x9a, 0x82, 0x90, 0x4c, 0xe6, 0xd1, 0xde, 0x10, 0x4d, 0xb5, 0x54, 0x97, 0x1a, 0x25, 0x23,
	0xde, 0x93, 0x3f, 0xa0, 0x78, 0xcc, 0x70, 0x68, 0x7a, 0xaa, 0x52, 0x97, 0x1b, 0x8a, 0x11, 0xed,
	0x92, 0x14, 0x43, 0x92, 0x62, 0xed, 0x0e, 0x2c, 0x4f, 0x45, 0x44, 0x7e, 0x03, 0xf9, 0x04, 0x7d,
	0xc1, 0xab, 0x62, 0x04, 0x4b, 0x52, 0x85, 0xc2, 0x29, 0x1d, 0x8e, 0xaf, 0x98, 0x0d, 0x37, 0xbb,
	0xb9, 0xdb, 0x92, 0xfe, 0x5a, 0x86, 0xda, 0x13, 0xc7, 0xa4, 0x8b, 0xca, 0xfd, 0x23, 0x25, 0x7a,
	0x3c, 0x43, 0xa2, 0x5b, 0xb1, 0x44, 0x19, 0x51, 0x7f, 0x47, 0x8d, 0x12, 0x5a, 0x28, 0x37, 0xab,
	0xc5, 0x03, 0x58, 0x35, 0x90, 0x9a, 0x37, 0xd0, 0x77, 0x3d, 0xa8, 0x75, 0x90, 0xba, 0x69, 0x7d,
	0x47, 0x20, 0xef, 0xd0, 0x01, 0x0a, 0xb4, 0x82, 0x21, 0xd6, 0x81, 0x4d, 0xe8, 0x93, 0x0b, 0x6d,
	0xc1, 0x3a, 0xe9, 0x43, 0x9e, 0xf2, 0xb1, 0x0f, 0xe4, 0x90, 0x79, 0x3c, 0xe9, 0x81, 0x6c, 0x43,
	0x81, 0x71, 0x1c, 0x79, 0xaa, 0x24, 0xe4, 0xfa, 0x33, 0x96, 0x6b, 0x2a, 0x92, 0xf0, 0x96, 0xfe,
	0x21, 0x0f, 0x95, 0x29, 0x84, 0xe9, 0x44, 0xd7, 0x00, 0xfa, 0x2e, 0x52, 0x8e, 0x66, 0x97, 0xf2,
	0x28, 0x53, 0x25, 0xb2, 0xdc, 0xe5, 0x64, 0xfb, 0xcb, 0x71, 0xcf, 0x17, 0x41, 0x96, 0xdb, 0x95,
	0x66, 0x38, 0xf5, 0x9a, 0x87, 0xb6, 0x7d, 0x32, 0x76, 0xe2, 0xeb, 0x7b, 0x7e, 0x80, 0x36, 0x16,
	0x85, 0x23, 0xd0, 0xc2, 0x62, 0x54, 0x22, 0x4b, 0x88, 0x76, 0x75, 0xdc, 0x0b, 0x0b, 0x72, 0x06,
	0x5a, 0x74, 0x63, 0xcf, 0x17, 0x04, 0x51, 0x4e, 0xc3, 0xca, 0x2e, 0x46, 0x04, 0x51, 0x4e, 0x45,
	0x69, 0xaf, 0x01, 0x88, 0xc3, 0xbe, 0x3d, 0xb6, 0xb8, 0xa8, 0x33, 0xd9, 0x10, 0xd7, 0xf7, 0x03,
	0x43, 0xdc, 0x49, 0xa5, 0xf4, 0x4e, 0x52, 0x32, 0x3b, 0x09, 0xd2, 0x3b, 0xa9, 0x3c, 0xd5, 0x49,
	0x04, 0xf2, 0xdc, 0x77, 0x50, 0xfd, 0x25, 0xf4, 0x15, 0xac, 0xc9, 0xfd, 0x44, 0x77, 0xfd, 0x2a,
	0xe4, 0xfa, 0x2f, 0x45, 0xae, 0xaf, 0x69, 0xa8, 0x4a, 0x76, 0x43, 0x2d, 0x27, 0x1b, 0xea, 0x5b,
	0x7b, 0xe6, 0x8d, 0x0c, 0xb5, 0x7d, 0xa1, 0x6e, 0x6a, 0xa9, 0x0b, 0x96, 0xa5, 0x74, 0x96, 0x73,
	0x99, 0x2c, 0xcb, 0xe9, 0x2c, 0xe7, 0x53, 0x58, 0x2e, 0x4c, 0xb0, 0x9c, 0x3d, 0xc3, 0x32, 0x22,
	0xff, 0x39, 0x67, 0x58, 0xfb, 0x6d, 0x11, 0x56, 0x92, 0xf9, 0x74, 0xd0, 0x3d, 0x65, 0x7d, 0x24,
	0x17, 0x50, 0x9d, 0x95, 0x2e, 0xd9, 0x5c, 0x84, 0x0d, 0x2d, 0x6d, 0x90, 0xe8, 0x9b, 0xaf, 0x3e,
	0x7e, 0x7a, 0x97, 0x5b, 0xd7, 0x57, 0x5b, 0xd1, 0x85, 0xd6, 0xd4, 0x8b, 0xc8, 0xdb, 0x95, 0xb6,
	0xc8, 0x73, 0xa8, 0xce, 0x1a, 0x88, 0x13, 0xce, 0x33, 0xe6, 0xa5, 0x56, 0x8b, 0x6f, 0x5d, 0x9f,
	0x78, 0xfa, 0x3f, 0x22, 0x80, 0x1a, 0x49, 0x0f, 0x80, 0xf8, 0x40, 0xae, 0x0f, 0x76, 0xa2, 0xc7,
	0xa8, 0xa9, 0x53, 0x3f, 0x3d, 0xed, 0x7f, 0x85, 0xd7, 0x3a, 0x59, 0x4f, 0xf5, 0xda, 0xba, 0x60,
	0xe6, 0x25, 0x79, 0x29, 0x41, 0x75, 0xd6, 0x9f, 0x72, 0x22, 0xf3, 0x8c, 0x1f, 0x69, 0xba, 0xff,
	0xff, 0x85, 0xff, 0x0d, 0x6d, 0x8e, 0xff, 0x80, 0xfb, 0x17, 0xf0, 0xfb, 0x8c, 0xe7, 0x14, 0xd9,
	0x58, 0xe0, 0xb1, 0x35, 0xd7, 0x7f, 0x7b, 0x01, 0xff, 0x97, 0x50, 0x9d, 0xf5, 0xa0, 0x9d, 0x60,
	0x20, 0xe3, 0xbd, 0x3b, 0x57, 0x81, 0xad, 0x39, 0x11, 0xf4, 0x8a, 0xe2, 0x59, 0xbd, 0xf3, 0x39,
	0x00, 0x00, 0xff, 0xff, 0x10, 0x55, 0xf6, 0x3b, 0xaa, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendProfileServiceClient is the client API for BackendProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendProfileServiceClient interface {
	// Create BackendProfile
	CreateBackendProfile(ctx context.Context, in *CreateBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error)
	// List of BackendProfile
	SearchBackendProfile(ctx context.Context, in *SearchBackendProfileRequest, opts ...grpc.CallOption) (*ListBackendProfile, error)
	// BackendProfile item
	ReadBackendProfile(ctx context.Context, in *ReadBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error)
	// Update BackendProfile
	UpdateBackendProfile(ctx context.Context, in *UpdateBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error)
	// Patch BackendProfile
	PatchBackendProfile(ctx context.Context, in *PatchBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error)
	// Remove BackendProfile
	DeleteBackendProfile(ctx context.Context, in *DeleteBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error)
}

type backendProfileServiceClient struct {
	cc *grpc.ClientConn
}

func NewBackendProfileServiceClient(cc *grpc.ClientConn) BackendProfileServiceClient {
	return &backendProfileServiceClient{cc}
}

func (c *backendProfileServiceClient) CreateBackendProfile(ctx context.Context, in *CreateBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error) {
	out := new(BackendProfile)
	err := c.cc.Invoke(ctx, "/storage.BackendProfileService/CreateBackendProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendProfileServiceClient) SearchBackendProfile(ctx context.Context, in *SearchBackendProfileRequest, opts ...grpc.CallOption) (*ListBackendProfile, error) {
	out := new(ListBackendProfile)
	err := c.cc.Invoke(ctx, "/storage.BackendProfileService/SearchBackendProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendProfileServiceClient) ReadBackendProfile(ctx context.Context, in *ReadBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error) {
	out := new(BackendProfile)
	err := c.cc.Invoke(ctx, "/storage.BackendProfileService/ReadBackendProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendProfileServiceClient) UpdateBackendProfile(ctx context.Context, in *UpdateBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error) {
	out := new(BackendProfile)
	err := c.cc.Invoke(ctx, "/storage.BackendProfileService/UpdateBackendProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendProfileServiceClient) PatchBackendProfile(ctx context.Context, in *PatchBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error) {
	out := new(BackendProfile)
	err := c.cc.Invoke(ctx, "/storage.BackendProfileService/PatchBackendProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendProfileServiceClient) DeleteBackendProfile(ctx context.Context, in *DeleteBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error) {
	out := new(BackendProfile)
	err := c.cc.Invoke(ctx, "/storage.BackendProfileService/DeleteBackendProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendProfileServiceServer is the server API for BackendProfileService service.
type BackendProfileServiceServer interface {
	// Create BackendProfile
	CreateBackendProfile(context.Context, *CreateBackendProfileRequest) (*BackendProfile, error)
	// List of BackendProfile
	SearchBackendProfile(context.Context, *SearchBackendProfileRequest) (*ListBackendProfile, error)
	// BackendProfile item
	ReadBackendProfile(context.Context, *ReadBackendProfileRequest) (*BackendProfile, error)
	// Update BackendProfile
	UpdateBackendProfile(context.Context, *UpdateBackendProfileRequest) (*BackendProfile, error)
	// Patch BackendProfile
	PatchBackendProfile(context.Context, *PatchBackendProfileRequest) (*BackendProfile, error)
	// Remove BackendProfile
	DeleteBackendProfile(context.Context, *DeleteBackendProfileRequest) (*BackendProfile, error)
}

// UnimplementedBackendProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBackendProfileServiceServer struct {
}

func (*UnimplementedBackendProfileServiceServer) CreateBackendProfile(ctx context.Context, req *CreateBackendProfileRequest) (*BackendProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBackendProfile not implemented")
}
func (*UnimplementedBackendProfileServiceServer) SearchBackendProfile(ctx context.Context, req *SearchBackendProfileRequest) (*ListBackendProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBackendProfile not implemented")
}
func (*UnimplementedBackendProfileServiceServer) ReadBackendProfile(ctx context.Context, req *ReadBackendProfileRequest) (*BackendProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBackendProfile not implemented")
}
func (*UnimplementedBackendProfileServiceServer) UpdateBackendProfile(ctx context.Context, req *UpdateBackendProfileRequest) (*BackendProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBackendProfile not implemented")
}
func (*UnimplementedBackendProfileServiceServer) PatchBackendProfile(ctx context.Context, req *PatchBackendProfileRequest) (*BackendProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchBackendProfile not implemented")
}
func (*UnimplementedBackendProfileServiceServer) DeleteBackendProfile(ctx context.Context, req *DeleteBackendProfileRequest) (*BackendProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBackendProfile not implemented")
}

func RegisterBackendProfileServiceServer(s *grpc.Server, srv BackendProfileServiceServer) {
	s.RegisterService(&_BackendProfileService_serviceDesc, srv)
}

func _BackendProfileService_CreateBackendProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackendProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendProfileServiceServer).CreateBackendProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.BackendProfileService/CreateBackendProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendProfileServiceServer).CreateBackendProfile(ctx, req.(*CreateBackendProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendProfileService_SearchBackendProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBackendProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendProfileServiceServer).SearchBackendProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.BackendProfileService/SearchBackendProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendProfileServiceServer).SearchBackendProfile(ctx, req.(*SearchBackendProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendProfileService_ReadBackendProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBackendProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendProfileServiceServer).ReadBackendProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.BackendProfileService/ReadBackendProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendProfileServiceServer).ReadBackendProfile(ctx, req.(*ReadBackendProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendProfileService_UpdateBackendProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBackendProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendProfileServiceServer).UpdateBackendProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.BackendProfileService/UpdateBackendProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendProfileServiceServer).UpdateBackendProfile(ctx, req.(*UpdateBackendProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendProfileService_PatchBackendProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchBackendProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendProfileServiceServer).PatchBackendProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.BackendProfileService/PatchBackendProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendProfileServiceServer).PatchBackendProfile(ctx, req.(*PatchBackendProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendProfileService_DeleteBackendProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackendProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendProfileServiceServer).DeleteBackendProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.BackendProfileService/DeleteBackendProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendProfileServiceServer).DeleteBackendProfile(ctx, req.(*DeleteBackendProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackendProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.BackendProfileService",
	HandlerType: (*BackendProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBackendProfile",
			Handler:    _BackendProfileService_CreateBackendProfile_Handler,
		},
		{
			MethodName: "SearchBackendProfile",
			Handler:    _BackendProfileService_SearchBackendProfile_Handler,
		},
		{
			MethodName: "ReadBackendProfile",
			Handler:    _BackendProfileService_ReadBackendProfile_Handler,
		},
		{
			MethodName: "UpdateBackendProfile",
			Handler:    _BackendProfileService_UpdateBackendProfile_Handler,
		},
		{
			MethodName: "PatchBackendProfile",
			Handler:    _BackendProfileService_PatchBackendProfile_Handler,
		},
		{
			MethodName: "DeleteBackendProfile",
			Handler:    _BackendProfileService_DeleteBackendProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend_profile.proto",
}
