// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend_profile.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackendProfile struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            int64             `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            *Lookup           `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            int64             `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            *Lookup           `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DataSize             int64             `protobuf:"varint,6,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	DataCount            int64             `protobuf:"varint,7,opt,name=data_count,json=dataCount,proto3" json:"data_count,omitempty"`
	Name                 string            `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	ExpireDays           int32             `protobuf:"varint,9,opt,name=expire_days,json=expireDays,proto3" json:"expire_days,omitempty"`
	MaxSize              int64             `protobuf:"varint,10,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Priority             int32             `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	Type                 *Lookup           `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	Properties           map[string]string `protobuf:"bytes,13,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Disabled             bool              `protobuf:"varint,15,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DomainId             int64             `protobuf:"varint,16,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BackendProfile) Reset()         { *m = BackendProfile{} }
func (m *BackendProfile) String() string { return proto.CompactTextString(m) }
func (*BackendProfile) ProtoMessage()    {}
func (*BackendProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{0}
}

func (m *BackendProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendProfile.Unmarshal(m, b)
}
func (m *BackendProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendProfile.Marshal(b, m, deterministic)
}
func (m *BackendProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendProfile.Merge(m, src)
}
func (m *BackendProfile) XXX_Size() int {
	return xxx_messageInfo_BackendProfile.Size(m)
}
func (m *BackendProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BackendProfile proto.InternalMessageInfo

func (m *BackendProfile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BackendProfile) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *BackendProfile) GetCreatedBy() *Lookup {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *BackendProfile) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *BackendProfile) GetUpdatedBy() *Lookup {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

func (m *BackendProfile) GetDataSize() int64 {
	if m != nil {
		return m.DataSize
	}
	return 0
}

func (m *BackendProfile) GetDataCount() int64 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BackendProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackendProfile) GetExpireDays() int32 {
	if m != nil {
		return m.ExpireDays
	}
	return 0
}

func (m *BackendProfile) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *BackendProfile) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *BackendProfile) GetType() *Lookup {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *BackendProfile) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *BackendProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BackendProfile) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *BackendProfile) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type LocalBackendProperties struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalBackendProperties) Reset()         { *m = LocalBackendProperties{} }
func (m *LocalBackendProperties) String() string { return proto.CompactTextString(m) }
func (*LocalBackendProperties) ProtoMessage()    {}
func (*LocalBackendProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{1}
}

func (m *LocalBackendProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalBackendProperties.Unmarshal(m, b)
}
func (m *LocalBackendProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalBackendProperties.Marshal(b, m, deterministic)
}
func (m *LocalBackendProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalBackendProperties.Merge(m, src)
}
func (m *LocalBackendProperties) XXX_Size() int {
	return xxx_messageInfo_LocalBackendProperties.Size(m)
}
func (m *LocalBackendProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalBackendProperties.DiscardUnknown(m)
}

var xxx_messageInfo_LocalBackendProperties proto.InternalMessageInfo

type S3BackendProperties struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3BackendProperties) Reset()         { *m = S3BackendProperties{} }
func (m *S3BackendProperties) String() string { return proto.CompactTextString(m) }
func (*S3BackendProperties) ProtoMessage()    {}
func (*S3BackendProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{2}
}

func (m *S3BackendProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3BackendProperties.Unmarshal(m, b)
}
func (m *S3BackendProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3BackendProperties.Marshal(b, m, deterministic)
}
func (m *S3BackendProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3BackendProperties.Merge(m, src)
}
func (m *S3BackendProperties) XXX_Size() int {
	return xxx_messageInfo_S3BackendProperties.Size(m)
}
func (m *S3BackendProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_S3BackendProperties.DiscardUnknown(m)
}

var xxx_messageInfo_S3BackendProperties proto.InternalMessageInfo

type CreateBackendProfileRequest struct {
	Name       string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpireDays int32   `protobuf:"varint,2,opt,name=expire_days,json=expireDays,proto3" json:"expire_days,omitempty"`
	MaxSize    int64   `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Priority   int32   `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Type       *Lookup `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Properties:
	//	*CreateBackendProfileRequest_Local
	//	*CreateBackendProfileRequest_S3
	Properties isCreateBackendProfileRequest_Properties `protobuf_oneof:"properties"`
	//    map<string,string> properties = 6;
	Description          string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Disabled             bool     `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DomainId             int64    `protobuf:"varint,10,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBackendProfileRequest) Reset()         { *m = CreateBackendProfileRequest{} }
func (m *CreateBackendProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBackendProfileRequest) ProtoMessage()    {}
func (*CreateBackendProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7b07ba17e92942, []int{3}
}

func (m *CreateBackendProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackendProfileRequest.Unmarshal(m, b)
}
func (m *CreateBackendProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackendProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateBackendProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackendProfileRequest.Merge(m, src)
}
func (m *CreateBackendProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBackendProfileRequest.Size(m)
}
func (m *CreateBackendProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackendProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackendProfileRequest proto.InternalMessageInfo

func (m *CreateBackendProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBackendProfileRequest) GetExpireDays() int32 {
	if m != nil {
		return m.ExpireDays
	}
	return 0
}

func (m *CreateBackendProfileRequest) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *CreateBackendProfileRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *CreateBackendProfileRequest) GetType() *Lookup {
	if m != nil {
		return m.Type
	}
	return nil
}

type isCreateBackendProfileRequest_Properties interface {
	isCreateBackendProfileRequest_Properties()
}

type CreateBackendProfileRequest_Local struct {
	Local *LocalBackendProperties `protobuf:"bytes,6,opt,name=local,proto3,oneof"`
}

type CreateBackendProfileRequest_S3 struct {
	S3 *S3BackendProperties `protobuf:"bytes,7,opt,name=s3,proto3,oneof"`
}

func (*CreateBackendProfileRequest_Local) isCreateBackendProfileRequest_Properties() {}

func (*CreateBackendProfileRequest_S3) isCreateBackendProfileRequest_Properties() {}

func (m *CreateBackendProfileRequest) GetProperties() isCreateBackendProfileRequest_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *CreateBackendProfileRequest) GetLocal() *LocalBackendProperties {
	if x, ok := m.GetProperties().(*CreateBackendProfileRequest_Local); ok {
		return x.Local
	}
	return nil
}

func (m *CreateBackendProfileRequest) GetS3() *S3BackendProperties {
	if x, ok := m.GetProperties().(*CreateBackendProfileRequest_S3); ok {
		return x.S3
	}
	return nil
}

func (m *CreateBackendProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateBackendProfileRequest) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *CreateBackendProfileRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateBackendProfileRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateBackendProfileRequest_Local)(nil),
		(*CreateBackendProfileRequest_S3)(nil),
	}
}

func init() {
	proto.RegisterType((*BackendProfile)(nil), "storage.BackendProfile")
	proto.RegisterMapType((map[string]string)(nil), "storage.BackendProfile.PropertiesEntry")
	proto.RegisterType((*LocalBackendProperties)(nil), "storage.LocalBackendProperties")
	proto.RegisterType((*S3BackendProperties)(nil), "storage.S3BackendProperties")
	proto.RegisterType((*CreateBackendProfileRequest)(nil), "storage.CreateBackendProfileRequest")
}

func init() { proto.RegisterFile("backend_profile.proto", fileDescriptor_5d7b07ba17e92942) }

var fileDescriptor_5d7b07ba17e92942 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xd1, 0x4e, 0xdb, 0x3c,
	0x14, 0xc7, 0x49, 0xd2, 0x42, 0x72, 0xc2, 0x07, 0xc8, 0x1f, 0x6c, 0xa6, 0xb0, 0x11, 0x75, 0x48,
	0x8b, 0x76, 0x91, 0x4a, 0xed, 0xc5, 0x26, 0xa4, 0x5d, 0xac, 0x6c, 0x1a, 0x93, 0xb8, 0x40, 0xe1,
	0x01, 0x2a, 0x37, 0xf6, 0x90, 0x45, 0x1a, 0x67, 0xb6, 0x8b, 0x08, 0xbb, 0x99, 0xf6, 0x0a, 0xdb,
	0x9b, 0xed, 0x15, 0x76, 0xbd, 0x67, 0x98, 0xe2, 0x84, 0xd0, 0xb2, 0xb6, 0x77, 0xf1, 0xff, 0x1c,
	0xff, 0x8f, 0xcf, 0xf9, 0x1d, 0x05, 0xf6, 0xc6, 0x24, 0xb9, 0x66, 0x19, 0x1d, 0xe5, 0x52, 0x7c,
	0xe6, 0x29, 0x8b, 0x72, 0x29, 0xb4, 0x40, 0x1b, 0x4a, 0x0b, 0x49, 0xae, 0x58, 0xc7, 0x4f, 0x44,
	0xa6, 0x74, 0xa5, 0x76, 0x0e, 0xaf, 0x84, 0xb8, 0x4a, 0x59, 0x8f, 0xe4, 0xbc, 0x47, 0xb2, 0x4c,
	0x68, 0xa2, 0xb9, 0xc8, 0x54, 0x15, 0xed, 0xfe, 0x69, 0xc1, 0xd6, 0xb0, 0x72, 0xbb, 0xa8, 0xcc,
	0xd0, 0x16, 0xd8, 0x9c, 0x62, 0x2b, 0xb0, 0x42, 0x27, 0xb6, 0x39, 0x45, 0xcf, 0x00, 0x12, 0xc9,
	0x88, 0x66, 0x74, 0x44, 0x34, 0xb6, 0x8d, 0xee, 0xd5, 0xca, 0x3b, 0x8d, 0xa2, 0x87, 0xf0, 0xb8,
	0xc0, 0x4e, 0x60, 0x85, 0x7e, 0x7f, 0x3b, 0xaa, 0x9f, 0x12, 0x9d, 0x0b, 0x71, 0x3d, 0xcd, 0x9b,
	0xfc, 0x61, 0x51, 0xda, 0x4d, 0x73, 0x7a, 0x6f, 0xd7, 0xaa, 0xec, 0x6a, 0xa5, 0xb2, 0xbb, 0x0f,
	0x8f, 0x0b, 0xdc, 0x5e, 0x62, 0x57, 0xa7, 0x0c, 0x0b, 0x74, 0x00, 0x1e, 0x25, 0x9a, 0x8c, 0x14,
	0xbf, 0x63, 0x78, 0xdd, 0xb8, 0xb9, 0xa5, 0x70, 0xc9, 0xef, 0x58, 0x59, 0xcb, 0x04, 0x13, 0x31,
	0xcd, 0x34, 0xde, 0xa8, 0x6a, 0x95, 0xca, 0x69, 0x29, 0x20, 0x04, 0xad, 0x8c, 0x4c, 0x18, 0x76,
	0x03, 0x2b, 0xf4, 0x62, 0xf3, 0x8d, 0x8e, 0xc0, 0x67, 0xb7, 0x39, 0x97, 0x6c, 0x44, 0x49, 0xa1,
	0xb0, 0x17, 0x58, 0x61, 0x3b, 0x86, 0x4a, 0x7a, 0x4f, 0x0a, 0x85, 0xf6, 0xc1, 0x9d, 0x90, 0xdb,
	0xaa, 0x1e, 0x18, 0xc7, 0x8d, 0x09, 0xb9, 0x35, 0xe5, 0x3a, 0xe0, 0xe6, 0x92, 0x0b, 0xc9, 0x75,
	0x81, 0x7d, 0x73, 0xb1, 0x39, 0xa3, 0x17, 0xd0, 0xd2, 0x45, 0xce, 0xf0, 0xe6, 0xe2, 0x8e, 0x4c,
	0x10, 0x7d, 0x04, 0xc8, 0xa5, 0xc8, 0x99, 0xd4, 0x9c, 0x29, 0xfc, 0x5f, 0xe0, 0x84, 0x7e, 0xff,
	0x65, 0x93, 0x3a, 0xcf, 0x29, 0xba, 0x68, 0x32, 0x3f, 0x64, 0x5a, 0x16, 0xf1, 0xcc, 0x55, 0x14,
	0x80, 0x4f, 0x99, 0x4a, 0x24, 0xcf, 0x4b, 0xd8, 0x78, 0xcb, 0x34, 0x38, 0x2b, 0x95, 0x6f, 0xa5,
	0x5c, 0x91, 0x71, 0xca, 0x28, 0xde, 0x0e, 0xac, 0xd0, 0x8d, 0x9b, 0xb3, 0x99, 0xa9, 0x98, 0x10,
	0x9e, 0x8d, 0x38, 0xc5, 0x3b, 0xf5, 0x4c, 0x8d, 0xf0, 0x89, 0x76, 0xde, 0xc2, 0xf6, 0xa3, 0xca,
	0x68, 0x07, 0x9c, 0x6b, 0x56, 0x98, 0x95, 0xf1, 0xe2, 0xf2, 0x13, 0xed, 0x42, 0xfb, 0x86, 0xa4,
	0x53, 0x66, 0xd6, 0xc5, 0x8b, 0xab, 0xc3, 0x89, 0xfd, 0xc6, 0xea, 0x62, 0x78, 0x72, 0x2e, 0x12,
	0x92, 0x3e, 0x34, 0x53, 0x5b, 0x75, 0xf7, 0xe0, 0xff, 0xcb, 0xc1, 0xbf, 0xf2, 0x37, 0x07, 0x0e,
	0x4e, 0xcd, 0xf6, 0xcc, 0xf7, 0x1f, 0xb3, 0x2f, 0x53, 0xa6, 0x1e, 0x20, 0x5a, 0xcb, 0x21, 0xda,
	0x2b, 0x21, 0x3a, 0xcb, 0x21, 0xb6, 0x96, 0x40, 0x6c, 0xaf, 0x82, 0xf8, 0x1a, 0xda, 0x69, 0xd9,
	0xa1, 0xd9, 0x46, 0xbf, 0x7f, 0x34, 0x93, 0xb5, 0xa8, 0xef, 0xb3, 0xb5, 0xb8, 0xca, 0x47, 0x11,
	0xd8, 0x6a, 0x60, 0xb6, 0xd4, 0xef, 0x1f, 0x36, 0xb7, 0x16, 0xcc, 0xe4, 0x6c, 0x2d, 0xb6, 0xd5,
	0xe0, 0x31, 0x64, 0x77, 0x35, 0x64, 0x6f, 0x15, 0x64, 0x98, 0x87, 0x3c, 0xdc, 0x9c, 0x5d, 0xc4,
	0xfe, 0x4f, 0x0b, 0xf6, 0xe6, 0x87, 0x7f, 0xc9, 0xe4, 0x0d, 0x4f, 0x18, 0xfa, 0x0a, 0xbb, 0x8b,
	0xd8, 0xa0, 0xe3, 0xe6, 0xf9, 0x2b, 0xd0, 0x75, 0x9e, 0x2e, 0x59, 0xed, 0xee, 0xf1, 0xf7, 0x5f,
	0xbf, 0x7f, 0xd8, 0xcf, 0xbb, 0xfb, 0xbd, 0x3a, 0xa1, 0xf7, 0xe8, 0x8f, 0xa7, 0x4e, 0xac, 0x57,
	0xe3, 0x75, 0xf3, 0x0b, 0x1b, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x20, 0xd4, 0x35, 0x09, 0x0f,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendProfileServiceClient is the client API for BackendProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendProfileServiceClient interface {
	// Create CreateBackendProfile
	CreateBackendProfile(ctx context.Context, in *CreateBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error)
}

type backendProfileServiceClient struct {
	cc *grpc.ClientConn
}

func NewBackendProfileServiceClient(cc *grpc.ClientConn) BackendProfileServiceClient {
	return &backendProfileServiceClient{cc}
}

func (c *backendProfileServiceClient) CreateBackendProfile(ctx context.Context, in *CreateBackendProfileRequest, opts ...grpc.CallOption) (*BackendProfile, error) {
	out := new(BackendProfile)
	err := c.cc.Invoke(ctx, "/storage.BackendProfileService/CreateBackendProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendProfileServiceServer is the server API for BackendProfileService service.
type BackendProfileServiceServer interface {
	// Create CreateBackendProfile
	CreateBackendProfile(context.Context, *CreateBackendProfileRequest) (*BackendProfile, error)
}

// UnimplementedBackendProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBackendProfileServiceServer struct {
}

func (*UnimplementedBackendProfileServiceServer) CreateBackendProfile(ctx context.Context, req *CreateBackendProfileRequest) (*BackendProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBackendProfile not implemented")
}

func RegisterBackendProfileServiceServer(s *grpc.Server, srv BackendProfileServiceServer) {
	s.RegisterService(&_BackendProfileService_serviceDesc, srv)
}

func _BackendProfileService_CreateBackendProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackendProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendProfileServiceServer).CreateBackendProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.BackendProfileService/CreateBackendProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendProfileServiceServer).CreateBackendProfile(ctx, req.(*CreateBackendProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackendProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.BackendProfileService",
	HandlerType: (*BackendProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBackendProfile",
			Handler:    _BackendProfileService_CreateBackendProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend_profile.proto",
}
