#!/usr/bin/env bash

SD=/etc/systemd/system/storage.service

if [ ! -f "$SD" ]; then
	curl -o $SD https://git.webitel.com/projects/WEP/repos/webitel/raw/etc/systemd/system/storage.service
fi

systemctl enable storage
systemctl restart storage

exit 0
